CREATE DATABASE Supply_Chain;
USE Supply_Chain;

ALTER TABLE supply_chain_dataset
RENAME COLUMN `Product type` TO product_type;

# Show all skincare products with price greater than 50.
SELECT SKU, Price, Product_type
FROM supply_chain_dataset
WHERE Product_type = 'skincare'
AND Price > 10;

# Find the top 10 most expensive products.
SELECT SKU, Price
FROM supply_chain_dataset
ORDER BY Price DESC
LIMIT 10;

# Find total revenue generated by each product category.
SELECT Product_type,
       SUM(`Revenue generated`) AS total_revenue
FROM supply_chain_dataset
GROUP BY Product_type;

# Find average manufacturing cost for each transportation mode.
SELECT `Transportation modes`,
       AVG(`Manufacturing costs`) AS avg_cost
FROM supply_chain_dataset
GROUP BY `Transportation modes`;

# Find products with low stock levels (less than 10).
SELECT SKU,
       `Stock levels`,
       Availability
FROM supply_chain_dataset
WHERE `Stock levels` < 10;

# Which supplier generated the highest revenue?
SELECT `Supplier name`,
       SUM(`Revenue generated`) AS revenue
FROM supply_chain_dataset
GROUP BY `Supplier name`
ORDER BY revenue DESC;

# Classify defect rates into Risk Levels.
SELECT SKU,
       `Defect rates`,
       CASE
           WHEN `Defect rates` < 1 THEN 'Low Risk'
           WHEN `Defect rates` < 3 THEN 'Medium Risk'
           ELSE 'High Risk'
       END AS risk_level
FROM supply_chain_dataset;

# Find suppliers whose average defect rate is above 3.
SELECT `Supplier name`,
       AVG(`Defect rates`) AS avg_defect_rate
FROM supply_chain_dataset
GROUP BY `Supplier name`
HAVING AVG(`Defect rates`) > 2;

# Rank products based on revenue.
SELECT SKU,
       `Revenue generated`,
       RANK() OVER (ORDER BY `Revenue generated` DESC) AS revenue_rank
FROM supply_chain_dataset;

# Find top 3 products from each product category.
SELECT *
FROM (
    SELECT SKU,
           Product_type,
           `Revenue generated`,
           DENSE_RANK() OVER (
               PARTITION BY Product_type
               ORDER BY `Revenue generated` DESC
           ) AS rank_num
    FROM supply_chain_dataset
) ranked
WHERE rank_num <= 3;

# Find products whose revenue is above average revenue.
SELECT SKU,
       `Revenue generated`
FROM supply_chain_dataset
WHERE `Revenue generated` >
(
    SELECT AVG(`Revenue generated`)
    FROM supply_chain_dataset
);

# Find whether longer shipping times lead to higher shipping costs.
SELECT `Shipping times`,
       AVG(`Shipping costs`) AS avg_shipping_cost
FROM supply_chain_dataset
GROUP BY `Shipping times`
ORDER BY `Shipping times`;

# Which transportation mode has the lowest average cost?
SELECT `Transportation modes`,
       AVG(Costs) AS avg_transport_cost
FROM supply_chain_dataset
GROUP BY `Transportation modes`
ORDER BY avg_transport_cost;

# Count products based on inspection results.
SELECT `Inspection results`,
       COUNT(*) AS total_products
FROM supply_chain_dataset
GROUP BY `Inspection results`;

# Create a mini business dashboard.
SELECT
    COUNT(*) AS total_products,
    SUM(`Revenue generated`) AS total_revenue,
    AVG(`Defect rates`) AS avg_defect_rate,
    AVG(`Shipping costs`) AS avg_shipping_cost,
    SUM(`Number of products sold`) AS total_units_sold
FROM supply_chain_dataset;

-- A company wants to identify:
-- High revenue products
-- With low defect rates
-- And low shipping costs
-- These products should be prioritized.
SELECT SKU,
       Product_type,
       `Revenue generated`,
       `Defect rates`,
       `Shipping costs`
FROM supply_chain_dataset
WHERE `Revenue generated` > 5000
AND `Defect rates` < 2
AND `Shipping costs` < 300
ORDER BY `Revenue generated` DESC;


# Find the best-performing supplier based on revenue and defect rate.
WITH supplier_summary AS (
    SELECT
        `Supplier name`,
        SUM(`Revenue generated`) AS total_revenue,
        AVG(`Defect rates`) AS avg_defect_rate
    FROM supply_chain_dataset
    GROUP BY `Supplier name`
)
SELECT *
FROM supplier_summary
ORDER BY total_revenue DESC,
         avg_defect_rate ASC;


# Identify bottlenecks in supply chain.

SELECT SKU,
       `Lead times`,
       `Manufacturing lead time`,
       `Shipping times`,
       (
         `Lead times` +
         `Manufacturing lead time` +
         `Shipping times`
       ) AS total_supply_chain_time
FROM supply_chain_dataset
ORDER BY total_supply_chain_time DESC;

